---
all:
  children:
    coordinators:
      hosts:
        coordinator.example.internal:
    workers:
      hosts:
        worker-01.example.internal:
        worker-02.example.internal:
        worker-03.example.internal:
        worker-04.example.internal:
    optional_build_nodes:
      hosts:
        build-node.example.internal:
