// Contract and correctness validation for the game artifacts, split into two
// independent concerns that must never be conflated:
//
// - The REAL Connection Guesser pool (public/data/game/*.json) is generated
//   by the Python catalog/graph-core pipeline
//   (`networked-players-catalog build-connection-rounds`), not by this
//   repo's own code. It is re-verified here from first principles two ways
//   (ADR 0043, corrective slice 4.5):
//     1. EXACT equality against universe.v1.json's own published credits[]
//        -- which is a COMPLETE per-album eligible-performer index (every
//        credit, not just the ones cited as a round's evidence), so a
//        round's answer_set/bridge_answer_sets can be checked for exact
//        agreement with an independently recomputed intersection, not just
//        containment.
//     2. A one-directional role-eligibility spot-check against
//        challenge.v2.json's own published credit rows, using an
//        independent TypeScript port of the Python performer-role allowlist
//        (not an import) -- catches a real allowlist regression that (1)
//        alone cannot, since (1) trusts the universe's own role filtering.
//        challenge.v2.json is pre-filtered for an unrelated path-discovery
//        process and routinely under-reports real credits, so this
//        direction only (real-derivable => published) is sound; the
//        opposite direction is check (1)'s job now, not this one's.
// - The SYNTHETIC test fixture (tests/fixtures/game-*.synthetic.v1.json) is
//   generated by scripts/build-rounds.mjs and exercised via --check
//   (drift + internal validation), same as before -- it is a test fixture
//   only and must never be mistaken for production data.

import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test } from "@playwright/test";
import type { ChallengeV2 } from "../src/data/challenge";
import type { GameRounds, GameUniverse } from "../src/game/types";

const webRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

const universe = JSON.parse(
  readFileSync(join(webRoot, "public/data/game/universe.v1.json"), "utf8"),
) as GameUniverse;
const roundsArtifact = JSON.parse(
  readFileSync(join(webRoot, "public/data/game/rounds.v1.json"), "utf8"),
) as GameRounds;
const challenge = JSON.parse(
  readFileSync(join(webRoot, "public/data/challenge.v2.json"), "utf8"),
) as ChallengeV2;

const syntheticUniverse = JSON.parse(
  readFileSync(
    join(webRoot, "tests/fixtures/game-universe.synthetic.v1.json"),
    "utf8",
  ),
) as GameUniverse;
const syntheticRounds = JSON.parse(
  readFileSync(
    join(webRoot, "tests/fixtures/game-rounds.synthetic.v1.json"),
    "utf8",
  ),
) as GameRounds;

const FORBIDDEN_SUBSTRINGS = [
  "/home/",
  "data/private",
  "local" + "/",
  ".ssh",
  "DISCOGS_TOKEN",
];
const FORBIDDEN_PHRASES = ["worked with", "collaborated with", "influenced"];

function assertNoForbiddenContent(label: string, artifact: unknown) {
  const lowered = JSON.stringify(artifact).toLowerCase();
  for (const substring of FORBIDDEN_SUBSTRINGS) {
    expect(
      lowered.includes(substring.toLowerCase()),
      `${label} must not contain ${substring}`,
    ).toBe(false);
  }
  for (const phrase of FORBIDDEN_PHRASES) {
    expect(
      lowered.includes(phrase),
      `${label} must not contain "${phrase}"`,
    ).toBe(false);
  }
}

// === Real pool: public/data/game/*.json =====================================

// Independent port of packages/graph-core's eligibility.py performer-role
// allowlist -- a different-language re-derivation, not an import, so a typo
// or logic bug in the Python module isn't graded by its own copy. Matches
// this file's existing precedent of duplicating small policy constants
// (see PLACEHOLDER_ARTIST_IDS in scripts/build-rounds.mjs).
const PERFORMER_ROLE_TOKENS = new Set([
  "vocals",
  "lead vocals",
  "co-lead vocals",
  "backing vocals",
  "background vocals",
  "additional vocals",
  "choir",
  "chorus",
  "voice",
  "rap",
  "spoken word",
  "guitar",
  "acoustic guitar",
  "electric guitar",
  "lead guitar",
  "rhythm guitar",
  "slide guitar",
  "steel guitar",
  "pedal steel",
  "bass",
  "bass guitar",
  "double bass",
  "upright bass",
  "banjo",
  "mandolin",
  "ukulele",
  "sitar",
  "violin",
  "viola",
  "cello",
  "fiddle",
  "harp",
  "drums",
  "percussion",
  "congas",
  "bongos",
  "timpani",
  "tabla",
  "piano",
  "electric piano",
  "organ",
  "hammond organ",
  "keyboards",
  "synthesizer",
  "synth",
  "accordion",
  "harpsichord",
  "celesta",
  "vibraphone",
  "marimba",
  "xylophone",
  "trumpet",
  "trombone",
  "tuba",
  "french horn",
  "cornet",
  "flugelhorn",
  "saxophone",
  "alto saxophone",
  "tenor saxophone",
  "baritone saxophone",
  "soprano saxophone",
  "clarinet",
  "flute",
  "piccolo",
  "oboe",
  "bassoon",
  "bagpipes",
  "harmonica",
]);

function isPerformerRole(roleText: string | null): boolean {
  if (roleText === null) return false;
  return roleText.split(",").some((component) =>
    PERFORMER_ROLE_TOKENS.has(
      component
        .replace(/\[.*\]/g, "")
        .trim()
        .toLowerCase(),
    ),
  );
}

/** artist_id -> set of real album ids (challenge.v2.json's AlbumV2.id) where
 * that artist holds an explicit, eligible performer credit on the album's
 * own main_release_id, per challenge.v2.json's OWN (narrower, differently-
 * filtered) evidence. Role-eligibility spot-check only -- see the file
 * header for why this can't support an exact-equality claim. */
function realPerformersByAlbum(): Map<string, Set<number>> {
  const releaseById = new Map(challenge.releases.map((r) => [r.release_id, r]));
  const result = new Map<string, Set<number>>();
  for (const album of challenge.albums) {
    const release = releaseById.get(album.main_release_id);
    const performers = new Set<number>();
    if (release) {
      for (const credit of release.credits) {
        if (credit.artist_id !== null && isPerformerRole(credit.role_text)) {
          performers.add(credit.artist_id);
        }
      }
    }
    result.set(album.id, performers);
  }
  return result;
}

/** artist_id -> set of real album ids where that artist appears in
 * universe.v1.json's OWN `credits[]` -- a COMPLETE per-album eligible-
 * performer index (every credit the Python generator found, not only the
 * ones cited as some round's evidence). This is what makes an EXACT
 * equality check possible: recompute the intersection between any two
 * albums from this data alone and compare it directly against a round's
 * published answer_set/bridge_answer_sets, in both directions. */
function universePerformersByAlbum(): Map<string, Set<number>> {
  const result = new Map<string, Set<number>>();
  for (const album of universe.albums) result.set(album.id, new Set());
  for (const credit of universe.credits) {
    result.get(credit.release_id)?.add(credit.contributor_id);
  }
  return result;
}

function sharedPerformers(
  byAlbum: Map<string, Set<number>>,
  albumAId: string,
  albumCId: string,
): Set<number> {
  const a = byAlbum.get(albumAId) ?? new Set<number>();
  const c = byAlbum.get(albumCId) ?? new Set<number>();
  return new Set([...a].filter((id) => c.has(id)));
}

function idSet(refs: { id: number }[]): Set<number> {
  return new Set(refs.map((r) => r.id));
}

function setsEqual(a: Set<number>, b: Set<number>): boolean {
  return a.size === b.size && [...a].every((id) => b.has(id));
}

test("real pool meets the launch floor (>=50 one-hop, >=20 two-hop)", () => {
  const oneHop = roundsArtifact.rounds.filter((r) => r.kind === "one_hop");
  const twoHop = roundsArtifact.rounds.filter((r) => r.kind === "two_hop");
  expect(oneHop.length).toBeGreaterThanOrEqual(50);
  expect(twoHop.length).toBeGreaterThanOrEqual(20);
  for (const round of roundsArtifact.rounds) {
    expect(round.pool, `round ${round.id} must be real-records`).toBe(
      "real-records",
    );
  }
});

test("real pool: answer_set exactly matches the universe's own shared-performer index (first principles, exact)", () => {
  const byAlbum = universePerformersByAlbum();
  for (const round of roundsArtifact.rounds) {
    if (round.kind !== "one_hop") continue;
    const [a, c] = round.endpoints;
    const derived = sharedPerformers(byAlbum, a.id, c.id);
    const published = idSet(round.answer_set);
    expect(
      setsEqual(derived, published),
      `round ${round.id}: answer_set [${[...published]}] does not exactly match ` +
        `the universe-derived shared performers [${[...derived]}]`,
    ).toBe(true);
  }
});

test("real pool: two-hop bridge_answer_sets exactly match the universe's own shared-performer index (first principles, exact)", () => {
  const byAlbum = universePerformersByAlbum();
  for (const round of roundsArtifact.rounds) {
    if (round.kind !== "two_hop" || !round.middle || !round.bridge_answer_sets) continue;
    const [a, c] = round.endpoints;
    const middleId = round.middle.album.id;
    const derivedA = sharedPerformers(byAlbum, a.id, middleId);
    const derivedC = sharedPerformers(byAlbum, middleId, c.id);
    const [publishedA, publishedC] = round.bridge_answer_sets;
    expect(
      setsEqual(derivedA, idSet(publishedA)),
      `round ${round.id}: bridge_a [${[...idSet(publishedA)]}] does not exactly match [${[...derivedA]}]`,
    ).toBe(true);
    expect(
      setsEqual(derivedC, idSet(publishedC)),
      `round ${round.id}: bridge_c [${[...idSet(publishedC)]}] does not exactly match [${[...derivedC]}]`,
    ).toBe(true);
    // The premise of a two-hop round: no direct shared performer between the
    // two endpoints (else it should have been generated as a one-hop round).
    expect(
      sharedPerformers(byAlbum, a.id, c.id).size,
      `round ${round.id}: endpoints share a direct performer -- should be one-hop`,
    ).toBe(0);
  }
});

test("real pool: every real-derivable shared performer is a published answer (role-eligibility spot-check, subset)", () => {
  // challenge.v2.json's releases[].credits[] is EvidenceRelease-shaped: pre-
  // filtered to whichever artists happen to be endpoints of *that separate
  // artifact's own* path discovery (a different generator, a different
  // question -- see challenge.ts's EvidenceRelease comment). It routinely
  // omits a real credit the Guesser's own generator legitimately found
  // (confirmed: e.g. Futuresex/Lovesounds <-> Still Bill's real session
  // players are absent from challenge.v2.json's filtered evidence entirely).
  // So this can only check one direction safely -- but it exercises an
  // INDEPENDENT role-allowlist port the exact-equality checks above don't,
  // since those trust universe.v1.json's own (Python-filtered) credits.
  const byAlbum = realPerformersByAlbum();
  for (const round of roundsArtifact.rounds) {
    if (round.kind !== "one_hop") continue;
    const [a, c] = round.endpoints;
    const performersA = byAlbum.get(a.id) ?? new Set();
    const performersC = byAlbum.get(c.id) ?? new Set();
    const derivedShared = [...performersA].filter((id) => performersC.has(id));
    const actualAnswers = new Set(round.answer_set.map((r) => r.id));
    for (const id of derivedShared) {
      expect(
        actualAnswers.has(id),
        `round ${round.id}: artist ${id} is a real shared performer per challenge.v2.json but missing from answer_set`,
      ).toBe(true);
    }
  }
});

test("real pool: round ids are stable, content-derived, and unique", () => {
  const seen = new Set<string>();
  for (const round of roundsArtifact.rounds) {
    expect(round.id).toMatch(/^conn-[0-9a-f]{10}$/);
    expect(seen.has(round.id), `duplicate round id ${round.id}`).toBe(false);
    seen.add(round.id);
  }
});

test("real pool: provenance records catalog_version/pool_version and matches across artifacts", () => {
  expect(universe.provenance.catalog_version).toBeTruthy();
  expect(universe.provenance.pool_version).toBeTruthy();
  expect(universe.provenance).toEqual(roundsArtifact.provenance);
});

test("real pool: multi-answer rounds' clues never imply a single exclusive answer", () => {
  for (const round of roundsArtifact.rounds) {
    if (round.kind === "one_hop" && round.answer_set.length > 1) {
      const roleClue = round.clues.find((c) => c.kind === "role");
      const initialsClue = round.clues.find((c) => c.kind === "initials");
      expect(roleClue?.text, `round ${round.id} role clue`).toContain(
        "among other valid answers",
      );
      expect(initialsClue?.text, `round ${round.id} initials clue`).toContain(
        "one of several valid answers",
      );
    }
    if (round.kind === "two_hop" && round.bridge_answer_sets) {
      const [bridgeA, bridgeC] = round.bridge_answer_sets;
      if (bridgeA.length > 1 || bridgeC.length > 1) {
        const roleClue = round.clues.find((c) => c.kind === "role");
        expect(roleClue?.text, `round ${round.id} role clue`).toContain(
          "among other valid answers",
        );
      }
    }
  }
});

test("real pool: the hidden middle is not always the first choice", () => {
  const twoHop = roundsArtifact.rounds.filter((r) => r.kind === "two_hop" && r.middle);
  expect(twoHop.length).toBeGreaterThanOrEqual(20);
  const firstPositionCount = twoHop.filter(
    (r) => r.middle!.choices[0]?.id === r.middle!.album.id,
  ).length;
  expect(firstPositionCount).toBeLessThan(twoHop.length);
});

test("real distractors never satisfy the connection (first principles, exact)", () => {
  const byAlbum = universePerformersByAlbum();
  const legacyByAlbum = realPerformersByAlbum();
  for (const round of roundsArtifact.rounds) {
    const answerIds = new Set(round.answer_set.map((a) => a.id));
    for (const bridgeSet of round.bridge_answer_sets ?? []) {
      for (const a of bridgeSet) answerIds.add(a.id);
    }
    for (const distractor of round.distractors) {
      expect(
        answerIds.has(distractor.id),
        `round ${round.id}: distractor ${distractor.name} is also an answer`,
      ).toBe(false);
    }
    if (round.kind === "one_hop") {
      const [a, c] = round.endpoints;
      const shared = sharedPerformers(byAlbum, a.id, c.id);
      const legacyA = legacyByAlbum.get(a.id) ?? new Set();
      const legacyC = legacyByAlbum.get(c.id) ?? new Set();
      for (const distractor of round.distractors) {
        expect(
          shared.has(distractor.id),
          `round ${round.id}: distractor ${distractor.name} is credited on both albums (universe)`,
        ).toBe(false);
        expect(
          legacyA.has(distractor.id) && legacyC.has(distractor.id),
          `round ${round.id}: distractor ${distractor.name} is credited on both albums (challenge.v2.json spot-check)`,
        ).toBe(false);
      }
    } else if (round.middle) {
      const [a, c] = round.endpoints;
      const middleId = round.middle.album.id;
      const sharedA = sharedPerformers(byAlbum, a.id, middleId);
      const sharedC = sharedPerformers(byAlbum, middleId, c.id);
      for (const distractor of round.distractors) {
        expect(
          sharedA.has(distractor.id) || sharedC.has(distractor.id),
          `round ${round.id}: distractor ${distractor.name} bridges a side`,
        ).toBe(false);
      }
    }
  }
});

test("every real round carries evidence for every answer and a provenance note", () => {
  for (const round of roundsArtifact.rounds) {
    expect(round.evidence.length).toBeGreaterThan(0);
    expect(round.provenance_note.length).toBeGreaterThan(10);
    const allAnswers = [
      ...round.answer_set,
      ...(round.bridge_answer_sets ?? []).flat(),
    ];
    for (const answer of allAnswers) {
      expect(
        round.evidence.some((row) => row.contributor_id === answer.id),
        `round ${round.id}: answer ${answer.name} lacks evidence rows`,
      ).toBe(true);
    }
    if (round.kind === "two_hop") {
      expect(round.middle).toBeTruthy();
      expect(round.bridge_answer_sets).toBeTruthy();
      expect(
        round.middle!.choices.some((c) => c.id === round.middle!.album.id),
      ).toBe(true);
    }
  }
});

test("real pool provenance identifies a real Discogs source, never synthetic", () => {
  const source = universe.provenance.source.toLowerCase();
  const generatedBy = universe.provenance.generated_by.toLowerCase();
  expect(source.includes("discogs")).toBe(true);
  expect(generatedBy.includes("synthetic")).toBe(false);
  expect(generatedBy.includes("ci placeholder")).toBe(false);
  for (const round of roundsArtifact.rounds) {
    expect(round.pool).toBe("real-records");
  }
});

test("real pool artifacts are free of forbidden substrings and influence phrasing", () => {
  assertNoForbiddenContent("universe.v1.json", universe);
  assertNoForbiddenContent("rounds.v1.json", roundsArtifact);
});

// === Synthetic test fixture: tests/fixtures/game-*.synthetic.v1.json ========

test("synthetic fixture: build-rounds --check passes (validation + no drift)", () => {
  execFileSync("node", ["scripts/build-rounds.mjs", "--check"], {
    cwd: webRoot,
    stdio: "pipe",
  });
});

test("synthetic fixture: running derivation twice is deterministic", () => {
  const first = execFileSync("node", ["scripts/build-rounds.mjs", "--check"], {
    cwd: webRoot,
    stdio: "pipe",
  }).toString();
  const second = execFileSync("node", ["scripts/build-rounds.mjs", "--check"], {
    cwd: webRoot,
    stdio: "pipe",
  }).toString();
  expect(first).toBe(second);
});

test("synthetic fixture: pool size and difficulty coverage meet the fixture's floor", () => {
  expect(syntheticRounds.rounds.length).toBeGreaterThanOrEqual(40);
  expect(
    syntheticRounds.rounds.filter((r) => r.kind === "two_hop").length,
  ).toBeGreaterThanOrEqual(8);
  for (const difficulty of ["easy", "medium", "hard"] as const) {
    expect(
      syntheticRounds.rounds.some((r) => r.difficulty === difficulty),
      `synthetic fixture needs a ${difficulty} round`,
    ).toBe(true);
  }
});

test("synthetic fixture: no distractor satisfies the connection (first principles)", () => {
  const releaseAlbum = new Map(
    syntheticUniverse.releases.map((r) => [r.id, r.album_id]),
  );
  const albumsByContributor = new Map<number, Set<string>>();
  for (const credit of syntheticUniverse.credits) {
    const albumId = releaseAlbum.get(credit.release_id)!;
    if (!albumsByContributor.has(credit.contributor_id))
      albumsByContributor.set(credit.contributor_id, new Set());
    albumsByContributor.get(credit.contributor_id)!.add(albumId);
  }
  for (const round of syntheticRounds.rounds) {
    const answerIds = new Set(round.answer_set.map((a) => a.id));
    for (const distractor of round.distractors) {
      expect(answerIds.has(distractor.id)).toBe(false);
      const albums = albumsByContributor.get(distractor.id) ?? new Set();
      const linksBoth = round.endpoints.every((e) => albums.has(e.id));
      expect(
        linksBoth,
        `round ${round.id}: distractor ${distractor.name} links both endpoints`,
      ).toBe(false);
    }
  }
});

test("synthetic fixture: every round carries evidence and a provenance note", () => {
  for (const round of syntheticRounds.rounds) {
    expect(round.evidence.length).toBeGreaterThan(0);
    expect(round.provenance_note.length).toBeGreaterThan(10);
    for (const answer of round.answer_set) {
      expect(
        round.evidence.some((row) => row.contributor_id === answer.id),
        `round ${round.id}: answer ${answer.name} lacks evidence rows`,
      ).toBe(true);
    }
    if (round.kind === "two_hop") {
      expect(round.middle).toBeTruthy();
      expect(round.bridge_answer_sets).toBeTruthy();
      expect(
        round.middle!.choices.some((c) => c.id === round.middle!.album.id),
      ).toBe(true);
    }
  }
});

test("synthetic fixture is free of forbidden substrings and influence phrasing", () => {
  assertNoForbiddenContent(
    "game-universe.synthetic.v1.json",
    syntheticUniverse,
  );
  assertNoForbiddenContent("game-rounds.synthetic.v1.json", syntheticRounds);
});

test("synthetic fixture self-identifies in isolation; ids stay in reserved ranges", () => {
  for (const field of ["source", "license", "note"] as const) {
    const value = syntheticUniverse.provenance[field].toLowerCase();
    expect(
      value.includes("synthetic") || value.includes("fiction"),
      `provenance.${field} must self-identify`,
    ).toBe(true);
  }
  for (const album of syntheticUniverse.albums)
    expect(album.id).toMatch(/^syn-a\d{2}$/);
  for (const c of syntheticUniverse.contributors)
    expect(c.id).toBeGreaterThanOrEqual(90000000);
  for (const round of syntheticRounds.rounds) {
    expect(round.pool).toBe("synthetic-universe");
    for (const e of round.endpoints) expect(e.id).toMatch(/^syn-a/);
    const hotlinked = round.endpoints.some(
      (e) => e.art !== null && e.art.kind === "hotlink",
    );
    expect(hotlinked, `round ${round.id} hotlinks art`).toBe(false);
  }
});
