// Contract and correctness validation for the game artifacts, split into two
// independent concerns that must never be conflated:
//
// - The REAL Connection Guesser pool (public/data/game/*.json) is generated
//   by the Python catalog/graph-core pipeline
//   (`networked-players-catalog build-connection-rounds`), not by this
//   repo's own code. It is re-verified here from first principles against
//   challenge.v2.json's own published credit rows -- an independent
//   re-derivation in a different language, so a bug in the Python
//   generator's own validator can't silently pass its own output.
// - The SYNTHETIC test fixture (tests/fixtures/game-*.synthetic.v1.json) is
//   generated by scripts/build-rounds.mjs and exercised via --check
//   (drift + internal validation), same as before -- it is a test fixture
//   only and must never be mistaken for production data.

import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test } from "@playwright/test";
import type { ChallengeV2 } from "../src/data/challenge";
import type { GameRounds, GameUniverse } from "../src/game/types";

const webRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

const universe = JSON.parse(
  readFileSync(join(webRoot, "public/data/game/universe.v1.json"), "utf8"),
) as GameUniverse;
const roundsArtifact = JSON.parse(
  readFileSync(join(webRoot, "public/data/game/rounds.v1.json"), "utf8"),
) as GameRounds;
const challenge = JSON.parse(
  readFileSync(join(webRoot, "public/data/challenge.v2.json"), "utf8"),
) as ChallengeV2;

const syntheticUniverse = JSON.parse(
  readFileSync(
    join(webRoot, "tests/fixtures/game-universe.synthetic.v1.json"),
    "utf8",
  ),
) as GameUniverse;
const syntheticRounds = JSON.parse(
  readFileSync(
    join(webRoot, "tests/fixtures/game-rounds.synthetic.v1.json"),
    "utf8",
  ),
) as GameRounds;

const FORBIDDEN_SUBSTRINGS = [
  "/home/",
  "data/private",
  "local" + "/",
  ".ssh",
  "DISCOGS_TOKEN",
];
const FORBIDDEN_PHRASES = ["worked with", "collaborated with", "influenced"];

function assertNoForbiddenContent(label: string, artifact: unknown) {
  const lowered = JSON.stringify(artifact).toLowerCase();
  for (const substring of FORBIDDEN_SUBSTRINGS) {
    expect(
      lowered.includes(substring.toLowerCase()),
      `${label} must not contain ${substring}`,
    ).toBe(false);
  }
  for (const phrase of FORBIDDEN_PHRASES) {
    expect(
      lowered.includes(phrase),
      `${label} must not contain "${phrase}"`,
    ).toBe(false);
  }
}

// === Real pool: public/data/game/*.json =====================================

// Independent port of packages/graph-core's eligibility.py performer-role
// allowlist -- a different-language re-derivation, not an import, so a typo
// or logic bug in the Python module isn't graded by its own copy. Matches
// this file's existing precedent of duplicating small policy constants
// (see PLACEHOLDER_ARTIST_IDS in scripts/build-rounds.mjs).
const PERFORMER_ROLE_TOKENS = new Set([
  "vocals",
  "lead vocals",
  "co-lead vocals",
  "backing vocals",
  "background vocals",
  "additional vocals",
  "choir",
  "chorus",
  "voice",
  "rap",
  "spoken word",
  "guitar",
  "acoustic guitar",
  "electric guitar",
  "lead guitar",
  "rhythm guitar",
  "slide guitar",
  "steel guitar",
  "pedal steel",
  "bass",
  "bass guitar",
  "double bass",
  "upright bass",
  "banjo",
  "mandolin",
  "ukulele",
  "sitar",
  "violin",
  "viola",
  "cello",
  "fiddle",
  "harp",
  "drums",
  "percussion",
  "congas",
  "bongos",
  "timpani",
  "tabla",
  "piano",
  "electric piano",
  "organ",
  "hammond organ",
  "keyboards",
  "synthesizer",
  "synth",
  "accordion",
  "harpsichord",
  "celesta",
  "vibraphone",
  "marimba",
  "xylophone",
  "trumpet",
  "trombone",
  "tuba",
  "french horn",
  "cornet",
  "flugelhorn",
  "saxophone",
  "alto saxophone",
  "tenor saxophone",
  "baritone saxophone",
  "soprano saxophone",
  "clarinet",
  "flute",
  "piccolo",
  "oboe",
  "bassoon",
  "bagpipes",
  "harmonica",
]);

function isPerformerRole(roleText: string | null): boolean {
  if (roleText === null) return false;
  return roleText.split(",").some((component) =>
    PERFORMER_ROLE_TOKENS.has(
      component
        .replace(/\[.*\]/g, "")
        .trim()
        .toLowerCase(),
    ),
  );
}

/** artist_id -> set of real album ids (challenge.v2.json's AlbumV2.id) where
 * that artist holds an explicit, eligible performer credit on the album's
 * own main_release_id -- the exact question a one-hop round's answer_set
 * claims to answer, re-derived independently from the published evidence. */
function realPerformersByAlbum(): Map<string, Set<number>> {
  const releaseById = new Map(challenge.releases.map((r) => [r.release_id, r]));
  const result = new Map<string, Set<number>>();
  for (const album of challenge.albums) {
    const release = releaseById.get(album.main_release_id);
    const performers = new Set<number>();
    if (release) {
      for (const credit of release.credits) {
        if (credit.artist_id !== null && isPerformerRole(credit.role_text)) {
          performers.add(credit.artist_id);
        }
      }
    }
    result.set(album.id, performers);
  }
  return result;
}

test("real pool meets the launch floor (>=50 one-hop, >=20 two-hop)", () => {
  const oneHop = roundsArtifact.rounds.filter((r) => r.kind === "one_hop");
  const twoHop = roundsArtifact.rounds.filter((r) => r.kind === "two_hop");
  expect(oneHop.length).toBeGreaterThanOrEqual(50);
  expect(twoHop.length).toBeGreaterThanOrEqual(20);
  for (const round of roundsArtifact.rounds) {
    expect(round.pool, `round ${round.id} must be real-records`).toBe(
      "real-records",
    );
  }
});

test("every real-derivable shared performer is a published answer (first principles, subset check)", () => {
  // challenge.v2.json's releases[].credits[] is EvidenceRelease-shaped: pre-
  // filtered to whichever artists happen to be endpoints of *that separate
  // artifact's own* path discovery (a different generator, a different
  // question -- see challenge.ts's EvidenceRelease comment). It routinely
  // omits a real credit the Guesser's own generator legitimately found
  // (confirmed: e.g. Futuresex/Lovesounds <-> Still Bill's real session
  // players are absent from challenge.v2.json's filtered evidence entirely).
  // So this can only check one direction safely: whatever this narrower,
  // independently-filtered source DOES show as a real shared performer must
  // appear in the published answer_set -- true-positive containment, not
  // equality. A real generator bug that DROPPED a legitimate answer would
  // still be caught by this.
  const byAlbum = realPerformersByAlbum();
  for (const round of roundsArtifact.rounds) {
    if (round.kind !== "one_hop") continue;
    const [a, c] = round.endpoints;
    const performersA = byAlbum.get(a.id) ?? new Set();
    const performersC = byAlbum.get(c.id) ?? new Set();
    const derivedShared = [...performersA].filter((id) => performersC.has(id));
    const actualAnswers = new Set(round.answer_set.map((r) => r.id));
    for (const id of derivedShared) {
      expect(
        actualAnswers.has(id),
        `round ${round.id}: artist ${id} is a real shared performer per challenge.v2.json but missing from answer_set`,
      ).toBe(true);
    }
  }
});

test("real distractors never satisfy the connection (first principles)", () => {
  const byAlbum = realPerformersByAlbum();
  for (const round of roundsArtifact.rounds) {
    const answerIds = new Set(round.answer_set.map((a) => a.id));
    for (const bridgeSet of round.bridge_answer_sets ?? []) {
      for (const a of bridgeSet) answerIds.add(a.id);
    }
    for (const distractor of round.distractors) {
      expect(
        answerIds.has(distractor.id),
        `round ${round.id}: distractor ${distractor.name} is also an answer`,
      ).toBe(false);
    }
    if (round.kind === "one_hop") {
      const [a, c] = round.endpoints;
      const performersA = byAlbum.get(a.id) ?? new Set();
      const performersC = byAlbum.get(c.id) ?? new Set();
      for (const distractor of round.distractors) {
        const onBoth =
          performersA.has(distractor.id) && performersC.has(distractor.id);
        expect(
          onBoth,
          `round ${round.id}: distractor ${distractor.name} is credited on both albums`,
        ).toBe(false);
      }
    }
  }
});

test("every real round carries evidence for every answer and a provenance note", () => {
  for (const round of roundsArtifact.rounds) {
    expect(round.evidence.length).toBeGreaterThan(0);
    expect(round.provenance_note.length).toBeGreaterThan(10);
    const allAnswers = [
      ...round.answer_set,
      ...(round.bridge_answer_sets ?? []).flat(),
    ];
    for (const answer of allAnswers) {
      expect(
        round.evidence.some((row) => row.contributor_id === answer.id),
        `round ${round.id}: answer ${answer.name} lacks evidence rows`,
      ).toBe(true);
    }
    if (round.kind === "two_hop") {
      expect(round.middle).toBeTruthy();
      expect(round.bridge_answer_sets).toBeTruthy();
      expect(
        round.middle!.choices.some((c) => c.id === round.middle!.album.id),
      ).toBe(true);
    }
  }
});

test("real pool provenance identifies a real Discogs source, never synthetic", () => {
  const source = universe.provenance.source.toLowerCase();
  const generatedBy = universe.provenance.generated_by.toLowerCase();
  expect(source.includes("discogs")).toBe(true);
  expect(generatedBy.includes("synthetic")).toBe(false);
  expect(generatedBy.includes("ci placeholder")).toBe(false);
  for (const round of roundsArtifact.rounds) {
    expect(round.pool).toBe("real-records");
  }
});

test("real pool artifacts are free of forbidden substrings and influence phrasing", () => {
  assertNoForbiddenContent("universe.v1.json", universe);
  assertNoForbiddenContent("rounds.v1.json", roundsArtifact);
});

// === Synthetic test fixture: tests/fixtures/game-*.synthetic.v1.json ========

test("synthetic fixture: build-rounds --check passes (validation + no drift)", () => {
  execFileSync("node", ["scripts/build-rounds.mjs", "--check"], {
    cwd: webRoot,
    stdio: "pipe",
  });
});

test("synthetic fixture: running derivation twice is deterministic", () => {
  const first = execFileSync("node", ["scripts/build-rounds.mjs", "--check"], {
    cwd: webRoot,
    stdio: "pipe",
  }).toString();
  const second = execFileSync("node", ["scripts/build-rounds.mjs", "--check"], {
    cwd: webRoot,
    stdio: "pipe",
  }).toString();
  expect(first).toBe(second);
});

test("synthetic fixture: pool size and difficulty coverage meet the fixture's floor", () => {
  expect(syntheticRounds.rounds.length).toBeGreaterThanOrEqual(40);
  expect(
    syntheticRounds.rounds.filter((r) => r.kind === "two_hop").length,
  ).toBeGreaterThanOrEqual(8);
  for (const difficulty of ["easy", "medium", "hard"] as const) {
    expect(
      syntheticRounds.rounds.some((r) => r.difficulty === difficulty),
      `synthetic fixture needs a ${difficulty} round`,
    ).toBe(true);
  }
});

test("synthetic fixture: no distractor satisfies the connection (first principles)", () => {
  const releaseAlbum = new Map(
    syntheticUniverse.releases.map((r) => [r.id, r.album_id]),
  );
  const albumsByContributor = new Map<number, Set<string>>();
  for (const credit of syntheticUniverse.credits) {
    const albumId = releaseAlbum.get(credit.release_id)!;
    if (!albumsByContributor.has(credit.contributor_id))
      albumsByContributor.set(credit.contributor_id, new Set());
    albumsByContributor.get(credit.contributor_id)!.add(albumId);
  }
  for (const round of syntheticRounds.rounds) {
    const answerIds = new Set(round.answer_set.map((a) => a.id));
    for (const distractor of round.distractors) {
      expect(answerIds.has(distractor.id)).toBe(false);
      const albums = albumsByContributor.get(distractor.id) ?? new Set();
      const linksBoth = round.endpoints.every((e) => albums.has(e.id));
      expect(
        linksBoth,
        `round ${round.id}: distractor ${distractor.name} links both endpoints`,
      ).toBe(false);
    }
  }
});

test("synthetic fixture: every round carries evidence and a provenance note", () => {
  for (const round of syntheticRounds.rounds) {
    expect(round.evidence.length).toBeGreaterThan(0);
    expect(round.provenance_note.length).toBeGreaterThan(10);
    for (const answer of round.answer_set) {
      expect(
        round.evidence.some((row) => row.contributor_id === answer.id),
        `round ${round.id}: answer ${answer.name} lacks evidence rows`,
      ).toBe(true);
    }
    if (round.kind === "two_hop") {
      expect(round.middle).toBeTruthy();
      expect(round.bridge_answer_sets).toBeTruthy();
      expect(
        round.middle!.choices.some((c) => c.id === round.middle!.album.id),
      ).toBe(true);
    }
  }
});

test("synthetic fixture is free of forbidden substrings and influence phrasing", () => {
  assertNoForbiddenContent(
    "game-universe.synthetic.v1.json",
    syntheticUniverse,
  );
  assertNoForbiddenContent("game-rounds.synthetic.v1.json", syntheticRounds);
});

test("synthetic fixture self-identifies in isolation; ids stay in reserved ranges", () => {
  for (const field of ["source", "license", "note"] as const) {
    const value = syntheticUniverse.provenance[field].toLowerCase();
    expect(
      value.includes("synthetic") || value.includes("fiction"),
      `provenance.${field} must self-identify`,
    ).toBe(true);
  }
  for (const album of syntheticUniverse.albums)
    expect(album.id).toMatch(/^syn-a\d{2}$/);
  for (const c of syntheticUniverse.contributors)
    expect(c.id).toBeGreaterThanOrEqual(90000000);
  for (const round of syntheticRounds.rounds) {
    expect(round.pool).toBe("synthetic-universe");
    for (const e of round.endpoints) expect(e.id).toMatch(/^syn-a/);
    const hotlinked = round.endpoints.some(
      (e) => e.art !== null && e.art.kind === "hotlink",
    );
    expect(hotlinked, `round ${round.id} hotlinks art`).toBe(false);
  }
});
