#!/usr/bin/env bash
#
# Idempotently bring up the read-only catalog-data HTTP server
# (docker-compose.catalog-data.yml): LAN-bound nginx serving the processed
# dataset tree so remote workers can read data that lives only on this
# host's disk. Meant to be started deliberately before a remote-worker
# session and stopped after -- not a standing service. See
# docs/decisions/0024-http-readonly-catalog-data-access.md.
#
# Generates local/catalog-data.env (git-ignored) with an auto-detected LAN
# IP and the default processed-data path on first run, unless one already
# exists. Auto-detection never falls back to 0.0.0.0 -- if it can't
# determine a real LAN address, it aborts and asks you to set
# CATALOG_DATA_BIND_IP yourself (copy infra/swarm/catalog-data.env.example).
#
# Usage: ./infra/swarm/deploy-catalog-data.sh
#        ./infra/swarm/deploy-catalog-data.sh --down
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${SCRIPT_DIR}"

ENV_FILE="${REPO_ROOT}/local/catalog-data.env"

# shellcheck disable=SC1091
source "${SCRIPT_DIR}/../../scripts/lib/docker-compose.sh"
docker_sudo_setup docker-compose.catalog-data.yml

if [[ "${1:-}" == "--down" ]]; then
  echo "==> Stopping the catalog-data server."
  "${DC[@]}" --env-file "${ENV_FILE}" down
  exit 0
fi

mkdir -p "${REPO_ROOT}/local"

if [[ -f "${ENV_FILE}" ]]; then
  echo "==> ${ENV_FILE} already exists; leaving it as-is."
else
  echo "==> No ${ENV_FILE} found; generating one."
  lan_ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')"
  if [[ -z "${lan_ip}" ]]; then
    echo "ABORT: could not auto-detect a LAN IP." >&2
    echo "        cp catalog-data.env.example ${ENV_FILE} and set CATALOG_DATA_BIND_IP yourself." >&2
    exit 1
  fi
  umask 077
  {
    echo "# Generated by deploy-catalog-data.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "# Real LAN address and dataset path -- never commit this file."
    echo "CATALOG_DATA_BIND_IP=${lan_ip}"
    echo "CATALOG_DATA_PORT=8791"
    echo "CATALOG_DATA_DIR=${REPO_ROOT}/local/processed"
  } > "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  echo "==> Wrote ${ENV_FILE} (chmod 600), binding to detected LAN IP ${lan_ip}."
fi

# shellcheck disable=SC1090
source "${ENV_FILE}"
if [[ ! -d "${CATALOG_DATA_DIR}" ]]; then
  echo "ABORT: CATALOG_DATA_DIR=${CATALOG_DATA_DIR} does not exist -- nothing to serve." >&2
  echo "        Run a real parse first, or fix the path in ${ENV_FILE}." >&2
  exit 1
fi

echo "==> Bringing up the catalog-data server..."
"${DC[@]}" --env-file "${ENV_FILE}" up -d

echo "==> Waiting for it to report healthy (up to 30s)..."
healthy=0
for _ in $(seq 1 15); do
  if "${DC[@]}" --env-file "${ENV_FILE}" ps 2>/dev/null | grep -q '(healthy)'; then
    healthy=1
    break
  fi
  sleep 2
done

"${DC[@]}" --env-file "${ENV_FILE}" ps

if [[ "${healthy}" -eq 1 ]]; then
  echo "==> Catalog-data server healthy."
else
  echo "==> WARNING: not reported healthy within 30s; check above output." >&2
fi

echo "==> Datasets are now readable at http://${CATALOG_DATA_BIND_IP}:${CATALOG_DATA_PORT:-8791}/<dataset>/snapshot=<X>/..."
echo "==> Verify LAN-only (not 0.0.0.0) binding: ss -tln | grep ${CATALOG_DATA_PORT:-8791}"
echo "==> Stop it when done: ./infra/swarm/deploy-catalog-data.sh --down"
