#!/usr/bin/env bash
#
# Idempotently bring up the coordination-host Postgres/Redis stack
# (docker-compose.coordination.yml): Postgres 17 + Redis 7-alpine, both
# loopback-bound, pinned to this host simply by being a plain `docker
# compose` container here (not a Swarm service). Generates a real,
# git-ignored .env with a random Postgres password on first run if one
# doesn't exist yet; never commit .env. Brought up ahead of the NVMe per
# current eMMC headroom -- see
# docs/decisions/0010-coordination-stack-ahead-of-nvme.md.
#
# Usage: ./infra/swarm/deploy-coordination.sh
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

FLOOR_MB="${FLOOR_MB:-2000}"
free_mb=$(( $(df -Pk . | awk 'NR==2{print $4}') / 1024 ))
if (( free_mb < FLOOR_MB )); then
  echo "ABORT: only ${free_mb} MB free (floor: ${FLOOR_MB} MB)." >&2
  exit 1
fi
echo "==> Free space OK: ${free_mb} MB free (floor ${FLOOR_MB} MB)."

if [[ -f .env ]]; then
  echo "==> .env already exists; leaving it as-is."
else
  echo "==> No .env found; generating one with a random Postgres password."
  gen_pw="$(openssl rand -base64 24 | tr -d '\n')"
  umask 077
  {
    echo "# Generated by deploy-coordination.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "# Real credentials -- never commit this file."
    echo "POSTGRES_USER=networked_players"
    echo "POSTGRES_PASSWORD=${gen_pw}"
    echo "POSTGRES_DB=networked_players"
  } > .env
  chmod 600 .env
  echo "==> Wrote .env (chmod 600)."
fi

if ! id -nG "$(whoami)" | tr ' ' '\n' | grep -qx docker; then
  echo "==> Not in the docker group this session; using sudo."
  DC=(sudo docker compose -f docker-compose.coordination.yml)
else
  DC=(docker compose -f docker-compose.coordination.yml)
fi

# Not a plain count: docker-compose.coordination.yml and
# docker-compose.portainer.yml share an inferred project name ("swarm"), so
# `ps`/`--services` here lists every service in that project -- including
# portainer -- not just this file's own. Confirmed live. Check by name instead.
running_services="$("${DC[@]}" ps --status running --services 2>/dev/null || true)"
if grep -qx postgres <<<"${running_services}" && grep -qx redis <<<"${running_services}"; then
  echo "==> postgres and redis already running; nothing to do."
else
  echo "==> Bringing up postgres and redis..."
  "${DC[@]}" up -d
fi

echo "==> Waiting for both services to report healthy (up to 60s)..."
healthy=0
for _ in $(seq 1 30); do
  healthy_count="$("${DC[@]}" ps 2>/dev/null | grep -c '(healthy)' || true)"
  if [[ "${healthy_count}" -eq 2 ]]; then
    healthy=1
    break
  fi
  sleep 2
done

"${DC[@]}" ps

if [[ "${healthy}" -eq 1 ]]; then
  echo "==> Both services healthy."
else
  echo "==> WARNING: not both services reported healthy within 60s; check above output." >&2
fi

echo "==> Verify loopback-only binding: ss -tln | grep -E '5432|6379'"
echo "==> Verify .env is git-ignored: git check-ignore -v infra/swarm/.env"
