#!/usr/bin/env bash
#
# Idempotently bring up the dedicated jobs-broker Redis
# (docker-compose.jobs-broker.yml): LAN-bound, password-protected, meant to
# be started deliberately before a cluster-vs-single-node benchmark run and
# stopped after -- not a standing service. See
# docs/decisions/0019-cluster-benchmark-rq-job-broker.md.
#
# Generates local/jobs-broker.env (git-ignored) with a random password and an
# auto-detected LAN IP on first run, unless one already exists. Auto-detection
# never falls back to 0.0.0.0 -- if it can't determine a real LAN address, it
# aborts and asks you to set JOBS_BROKER_BIND_IP yourself in
# local/jobs-broker.env (copy infra/swarm/jobs-broker.env.example first).
#
# Usage: ./infra/swarm/deploy-jobs-broker.sh
#        ./infra/swarm/deploy-jobs-broker.sh --down
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${SCRIPT_DIR}"

ENV_FILE="${REPO_ROOT}/local/jobs-broker.env"

# shellcheck disable=SC1091
source "${SCRIPT_DIR}/../../scripts/lib/docker-compose.sh"
docker_sudo_setup docker-compose.jobs-broker.yml

if [[ "${1:-}" == "--down" ]]; then
  echo "==> Stopping the jobs broker."
  "${DC[@]}" --env-file "${ENV_FILE}" down
  exit 0
fi

FLOOR_MB="${FLOOR_MB:-500}"
free_mb=$(( $(df -Pk . | awk 'NR==2{print $4}') / 1024 ))
if (( free_mb < FLOOR_MB )); then
  echo "ABORT: only ${free_mb} MB free (floor: ${FLOOR_MB} MB)." >&2
  exit 1
fi
echo "==> Free space OK: ${free_mb} MB free (floor ${FLOOR_MB} MB)."

mkdir -p "${REPO_ROOT}/local"

if [[ -f "${ENV_FILE}" ]]; then
  echo "==> ${ENV_FILE} already exists; leaving it as-is."
else
  echo "==> No ${ENV_FILE} found; generating one."
  lan_ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')"
  if [[ -z "${lan_ip}" ]]; then
    echo "ABORT: could not auto-detect a LAN IP." >&2
    echo "        cp jobs-broker.env.example ${ENV_FILE} and set JOBS_BROKER_BIND_IP yourself." >&2
    exit 1
  fi
  # hex, not base64: this password gets embedded directly in a redis:// URL
  # (scripts/cluster-benchmark-distributed.sh) without percent-encoding --
  # base64's `/` and `+` characters would silently break URL authority
  # parsing (confirmed live: redis-py's Redis.from_url() mis-parsed the host
  # and port when a base64 password happened to contain a `/`).
  gen_pw="$(openssl rand -hex 24)"
  umask 077
  {
    echo "# Generated by deploy-jobs-broker.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "# Real LAN address and password -- never commit this file."
    echo "JOBS_BROKER_BIND_IP=${lan_ip}"
    echo "JOBS_BROKER_PORT=6380"
    echo "JOBS_BROKER_PASSWORD=${gen_pw}"
  } > "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  echo "==> Wrote ${ENV_FILE} (chmod 600), binding to detected LAN IP ${lan_ip}."
fi

echo "==> Bringing up the jobs broker..."
"${DC[@]}" --env-file "${ENV_FILE}" up -d

echo "==> Waiting for it to report healthy (up to 30s)..."
healthy=0
for _ in $(seq 1 15); do
  if "${DC[@]}" --env-file "${ENV_FILE}" ps 2>/dev/null | grep -q '(healthy)'; then
    healthy=1
    break
  fi
  sleep 2
done

"${DC[@]}" --env-file "${ENV_FILE}" ps

if [[ "${healthy}" -eq 1 ]]; then
  echo "==> Jobs broker healthy."
else
  echo "==> WARNING: not reported healthy within 30s; check above output." >&2
fi

echo "==> Verify LAN-only (not 0.0.0.0) binding: ss -tln | grep 6380"
echo "==> Verify local/jobs-broker.env is git-ignored: git check-ignore -v local/jobs-broker.env"
echo "==> Stop it when done benchmarking: ./infra/swarm/deploy-jobs-broker.sh --down"
